project:
  type: website
  output-dir: docs

website:
  title: "Danping's Page"
  navbar:
    left:
      - href: index.qmd
        text: Home

      

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true



